### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by JadeVexo** [m2-farzan/ros2-humble-PKGBUILD#12]
Is this a working package? On a relatively new arch system I have used yay -Syu ros2-humble and it always breaks in installation and exits.

**Comment by brkay54** [comment]
[This](https://github.com/m2-farzan/ros2-galactic-PKGBUILD/issues/9) solved my installation problem recently.

**Comment by m2-farzan** [comment]
@JadeVexo sorry I was too busy to respond at the time. I assume you have found a way around the problem by now, so I'm closing this. If you still face the issue, please make another PR with a more descriptive title & description so that we can help!
