### ISSUE TITLE
 colcon: error: unrecognized arguments: --cmake-args -Wno-dev

### ISSUE THREAD

**Issue by douglasrizzo** [m2-farzan/ros2-humble-PKGBUILD#14]
Installing all dependencies works fine, but when yay gets to ros2-humble itself, I get the following error:

```
==> Sources are ready.
==> Making package: ros2-humble 2023.09.25-2 (Sun 05 Nov 2023 03:26:37 PM -03)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Removing existing $pkgdir/ directory...
==> Starting build()...
usage: colcon [-h] [--log-base LOG_BASE] [--log-level LOG_LEVEL]
              {build,test} ...
colcon: error: unrecognized arguments: --cmake-args -Wno-dev
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: ros2-humble-exit status 4
removing untracked AUR files from cache...
:: Cleaning (1/1): /home/dodo/.cache/yay/ros2-humble
 -> Failed to install the following packages. Manual intervention is required:
ros2-humble - exit status 4
```

Also, when I removed `--cmake-args -Wno-dev` from the erroring line inside PKGBUILD, the package installed correctly, but the contents of `/opt/ros/humble` seem incomplete:

```
> ls /opt/ros/humble
COLCON_IGNORE  local_setup.sh  _local_setup_util_sh.py  setup.sh
```

So I have no setup.bash or setup.zsh to source.

**Comment by douglasrizzo** [comment]
It looks like this package is installing an older version of colcon? I installed another version using pip, via `pip install -U colcon-common-extensions` and the installation moved forward a little bit. Now I am having a problem regarding the package `catkin_pkg` not being found.

**Comment by dimich-dmb** [comment]
https://github.com/m2-farzan/ros2-humble-PKGBUILD/pull/26
