### ISSUE TITLE
mimick_vendor build issue

### ISSUE THREAD

**Issue by TheSav1101** [m2-farzan/ros2-humble-PKGBUILD#17]
Hello, when I try to install this package I get this error:

```
--- stderr: mimick_vendor
Cloning into 'mimick-de11f8377eb95f932a03707b583bf3d4ce5bd3e7'...
HEAD is now at de11f83 Support raspberry pi zero (#21)
In file included from /usr/include/errno.h:25,
                 from /home/emanuele/ros2-humble/src/build/mimick_vendor/mimick-de11f8377eb95f932a03707b583bf3d4ce5bd3e7-prefix/src/mimick-de11f8377eb95f932a03707b583bf3d4ce5bd3e7/include/mimick/mock.h:27,
                 from /home/emanuele/ros2-humble/src/build/mimick_vendor/mimick-de11f8377eb95f932a03707b583bf3d4ce5bd3e7-prefix/src/mimick-de11f8377eb95f932a03707b583bf3d4ce5bd3e7/include/mimick/mimick.h:401,
                 from /home/emanuele/ros2-humble/src/build/mimick_vendor/mimick-de11f8377eb95f932a03707b583bf3d4ce5bd3e7-prefix/src/mimick-de11f8377eb95f932a03707b583bf3d4ce5bd3e7/test/test.c:1:
/usr/include/features.h:414:4: error: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror=cpp]
  414 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
      |    ^~~~~~~
In file included from /usr/include/errno.h:25,
                 from /home/emanuele/ros2-humble/src/build/mimick_vendor/mimick-de11f8377eb95f932a03707b583bf3d4ce5bd3e7-prefix/src/mimick-de11f8377eb95f932a03707b583bf3d4ce5bd3e7/include/mimick/mock.h:27,
                 from /home/emanuele/ros2-humble/src/build/mimick_vendor/mimick-de11f8377eb95f932a03707b583bf3d4ce5bd3e7-prefix/src/mimick-de11f8377eb95f932a03707b583bf3d4ce5bd3e7/include/mimick/mimick.h:401,
                 from /home/emanuele/ros2-humble/src/build/mimick_vendor/mimick-de11f8377eb95f932a03707b583bf3d4ce5bd3e7-prefix/src/mimick-de11f8377eb95f932a03707b583bf3d4ce5bd3e7/sample/strdup/test.c:1:
/usr/include/features.h:414:4: error: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror=cpp]
  414 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
      |    ^~~~~~~
cc1: all warnings being treated as errors
make[5]: *** [sample/strdup/CMakeFiles/strdup_test.dir/build.make:76: sample/strdup/CMakeFiles/strdup_test.dir/test.c.o] Error 1
make[4]: *** [CMakeFiles/Makefile2:318: sample/strdup/CMakeFiles/strdup_test.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
cc1: all warnings being treated as errors
make[5]: *** [test/CMakeFiles/mmk_test_c.dir/build.make:76: test/CMakeFiles/mmk_test_c.dir/test.c.o] Error 1
make[4]: *** [CMakeFiles/Makefile2:238: test/CMakeFiles/mmk_test_c.dir/all] Error 2
make[3]: *** [Makefile:146: all] Error 2
make[2]: *** [CMakeFiles/mimick-de11f8377eb95f932a03707b583bf3d4ce5bd3e7.dir/build.make:86: mimick-de11f8377eb95f932a03707b583bf3d4ce5bd3e7-prefix/src/mimick-de11f8377eb95f932a03707b583bf3d4ce5bd3e7-stamp/mimick-de11f8377eb95f932a03707b583bf3d4ce5bd3e7-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:137: CMakeFiles/mimick-de11f8377eb95f932a03707b583bf3d4ce5bd3e7.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
---
Failed   <<< mimick_vendor [4.41s, exited with code 2]
```

I know this problem should have been fixed by:
```
unset CPPFLAGS
CFLAGS=$(sed "s/-Wp,-D_FORTIFY_SOURCE=3\s//g" <(echo $CFLAGS))
CXXFLAGS=$(sed "s/-Wp,-D_FORTIFY_SOURCE=3\s//g" <(echo $CXXFLAGS))
```

But it still persist with my installation...

Do you think this might be caused by commit 6924ed1? 
The other possible issue that comes to my mind is that I am trying to build it on manjaro and not plain arch, do you think that this might be a problem?

**Comment by m2-farzan** [comment]
Hey, do you have `pacman 6.1.0-3`? Can you upgrade to it? It may simply solve your problem.

If not, you may have to manually configure the CXX-related flags in your `/etc/makepkg.conf` file to match the ones in the PKGBUILD. This manual configuration may be needed either caused because pacman version is old, manjaro overrides something, or a there's conflict between your makepkg.conf and the upstream makepkg.conf which makes pacman go into conservative mode and never upgrade the conf file.

**Comment by petronny** [comment]
I suggest to use the following command to remove `_FORTIFY_SOURCE`, which is compatible with both `_FORTIFY_SOURCE=2` and `_FORTIFY_SOURCE=3`.
```
CFLAGS=$(sed "s/-Wp,-D_FORTIFY_SOURCE=[23]\s//g" <(echo $CFLAGS))
CXXFLAGS=$(sed "s/-Wp,-D_FORTIFY_SOURCE=[23]\s//g" <(echo $CXXFLAGS))
```

**Comment by TheSav1101** [comment]
> Hey, do you have `pacman 6.1.0-3`? Can you upgrade to it? It may simply solve your problem.
> 
> If not, you may have to manually configure the CXX-related flags in your `/etc/makepkg.conf` file to match the ones in the PKGBUILD. This manual configuration may be needed either caused because pacman version is old, manjaro overrides something, or a there's conflict between your makepkg.conf and the upstream makepkg.conf which makes pacman go into conservative mode and never upgrade the conf file.

I cannot upgrade pacman above version 6.0.2 (I mean I could if I decided to use the git version but I prefer to use binaries when available), do you know where I can find the upstream makepkg.conf? I have tried to find it, but I can't seem to ...



> I suggest to use the following command to remove `_FORTIFY_SOURCE`, which is compatible with both `_FORTIFY_SOURCE=2` and `_FORTIFY_SOURCE=3`.
> 
> ```
> CFLAGS=$(sed "s/-Wp,-D_FORTIFY_SOURCE=[23]\s//g" <(echo $CFLAGS))
> CXXFLAGS=$(sed "s/-Wp,-D_FORTIFY_SOURCE=[23]\s//g" <(echo $CXXFLAGS))
> ```

I tried this one already, but for some reason it did not work... Do you have any other ideas?

**Comment by petronny** [comment]
> do you know where I can find the upstream makepkg.conf

https://gitlab.archlinux.org/archlinux/packaging/packages/pacman/-/blob/main/makepkg.conf?ref_type=heads

But I don't think it's a good idea to install this configuration without upgrading pacman. It may break your system.

> I tried this one already, but for some reason it did not work... Do you have any other ideas?

You can see the actual flags in your system by adding
```
echo $CFLAGS
echo $CXXFLAGS
```
in PKGBUILD, then figure out how to adjust the flags according to your system.

**Comment by TheSav1101** [comment]
As you may imagine I am not very used to this, but I don't see FORTIFY_SOURCE in my flags...

```
-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -flto=auto
-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -flto=auto
```

do you know which one might be the culprit?

**Comment by petronny** [comment]
> As you may imagine I am not very used to this, but I don't see FORTIFY_SOURCE in my flags...

I have the same flags except `-flto=auto`. I don't think it's the culprit but you can disable it with `option=(!lto)`.

Maybe the error is not caused by `_FORTIFY_SOURCE` now. Could you check the build log?

**Comment by TheSav1101** [comment]
Ok, I just did a clean build of all the package and mimick_vendor compiled correctly with the same flags as my previous comment... So I guess that the solution suggested by @petronny was the correct one and I just had to 
`makepkg -Csi`
intstead of 
`makepkg -si`
Thank you everyone :D I still think that the lines in PKGBUILD should be changed  for other users who might have the same problem :)


Lines to change as in @petronny suggestion
> ```
> CFLAGS=$(sed "s/-Wp,-D_FORTIFY_SOURCE=[23]\s//g" <(echo $CFLAGS))
> CXXFLAGS=$(sed "s/-Wp,-D_FORTIFY_SOURCE=[23]\s//g" <(echo $CXXFLAGS))
> ```

My very last question is: should I close the issue or wait until this is patched? (pretty new to all this)

**Comment by m2-farzan** [comment]
Anyone interested in making a pull request for this? @TheSav1101 @petronny

**Comment by m2-farzan** [comment]
Nvm, I made the fix myself to save time: https://github.com/m2-farzan/ros2-humble-PKGBUILD/commit/4b61f612b91e5c9e9d8e757013b1868c2ce0d819

Thanks a lot for your report @TheSav1101 and your patch @petronny.
