### ISSUE TITLE
Simple change for interoperability with the `ros2-humble-base` package.

### ISSUE THREAD

**Issue by jack-obrien** [m2-farzan/ros2-humble-PKGBUILD#22]
Hi there, I notice that there is now a divide in the ROS2 aur world since the creation of the ros2-humble-base package. This is fine, however it would be good to allow these two separate packages to work together somewhat. 

My suggestion is for this package, `ros2-humble`, to list `ros2-humble-base` under provides and conflicts (refer to the pkgbuild docs for `provides` and `conflicts`: https://wiki.archlinux.org/title/PKGBUILD) . Then, any other packages can simply list a dependency on `ros2-humble-base` and maintain compatibility with both of the aur ros2 packages. Also, it will clarify to users that they cannot install both packages at the same time.

Happy to hear more suggestions!

**Comment by jack-obrien** [comment]
Note: Actually, it looks like ros2-humble-base uses a different install directory of /opt/ros/humble-base. So this fix would not be so easy...

I guess the main goal of this issue was to make all the extra packages work with just `ros2-humble-base`.

**Comment by oysstu** [comment]
I'm the maintainer of the ros2-humble-base package.  That package exists to provide a minimal installation for ROS2 development, without adding too many packages to maintain (e.g., rqt, rviz). I decided to put it in a separate directory in case someone wanted to have both installed at the same time, but it's probably a better idea to install into the same directory and conflict with ros2-humble as you suggest.  The ros2-humble package can then provide the ros2-humble-base package. I'll make the change on my end.

I originally planned on adding a few more packages in the same style, e.g. ros2-humble-perception.

**Comment by m2-farzan** [comment]
Thanks. I also made the required changes in #24.
